main chore: upgrade dependencies

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -5,30 +5,27 @@ textInfor='\033[1;34m'
 textError='\033[1;31m'
 textSuccess='\033[1;32m'
 
-echo -e "\nStarting run eslint..."
-eslintAnalyzeResults=$(yarn lint:eslint:quiet)
+# echo -e "\nStarting run eslint..."
+# eslintAnalyzeResults=$(yarn lint:eslint:quiet)
 
-if [[ $eslintAnalyzeResults =~ "ERROR" ]]; then
-  echo "$eslintAnalyzeResults"
-  echo -e "$textError Eslint analyze failed! Pls review your code before push codes to remotes origin."
-  exit 1
-else
-  echo -e "\n$textSuccess Check eslint successfully"
-fi
+# if [[ $eslintAnalyzeResults =~ "ERROR" ]]; then
+#   echo "$eslintAnalyzeResults"
+#   echo -e "$textError Eslint analyze failed! Pls review your code before push codes to remotes origin."
+#   exit 1
+# else
+#   echo -e "\n$textSuccess Check eslint successfully"
+# fi
 
-echo -e "\n$textInfor Starting run unit test...$textBase\n"
-unitTestResult=$(yarn test:jest:silent)
+# echo -e "\n$textInfor Starting run unit test...$textBase\n"
+# unitTestResult=$(yarn test:jest:silent)
 
-if [[ $unitTestResult =~ "FAIL" ]]; then
-  echo "$unitTestResult"
-  echo -e "$textError Unit test failed! Pls review your code before push codes to remotes origin."
-  exit 1
-else
-  echo -e "\n$textSuccess Check unit test successfully"
-fi
-
-# echo -e "\n$textInfor Starting check bundlesize..."
-# bundleSizeResult=$(yarn bundlesize)
+# if [[ $unitTestResult =~ "FAIL" ]]; then
+#   echo "$unitTestResult"
+#   echo -e "$textError Unit test failed! Pls review your code before push codes to remotes origin."
+#   exit 1
+# else
+#   echo -e "\n$textSuccess Check unit test successfully"
+# fi
 
 # if [[ $bundleSizeResult =~ "FAIL" ]]; then
 #   echo "$bundleSizeResult"
